apiVersion: v1
kind: Service
metadata:
  name: vikro-nginx
  labels:
    app: vikro-nginx
spec:
  type: LoadBalancer
  selector:
    app: vikro-nginx
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80